---
language: node_js
node_js:
- '0.10'

after_success:
- git config --global user.email "tracis@ci.org"
- git config --global user.name "Travis Bot"
- gulp ci:publishing

cache:
  directories:
    - node_modules
